spring:
  datasource:
    url: jdbc:oracle:thin:@db202201142010_medium?TNS_ADMIN=/Users/edward/Documents/Wallet_DB202201142010/
    username: ADMIN
    password: sMart2022@#$
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: oracle

#h2 console 활성화 및 경로 설정
#spring:
#  datasource:
#  url: jdbc:h2:~/test;
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#        show_sql: true
#    hibernate:
#      ddl-auto: validate
#  h2:
#    console:
#      enabled: true
#      path: /h2-console


